services:
  - type: web
    name: tra-vinh-pagoda-website
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: "/(.*)"
        destination: /index.html